const reviews = [{
  _id: '1',
  gameId: 0,
  date: `${new Date()}`,
  overall: 1,
  title: 'The Title',
  review: '',
  recommend: false,
  nickname: '',
  location: '',
  email: '',
  buyForSelf: false,
  ageBracket: 1,
  gender: 1,
  graphics: 1,
  gameplay: 1,
  appeal: 1,
  ownershipBracket: 1,
  purchaseOnline: true,
  readReviews: false,
  recommendBGS: 1,
  meta: {
    helpful: 1,
    unhelpful: 1,
  },
},
{
  _id: '2',
  gameId: 0,
  date: `${new Date()}`,
  overall: 1,
  title: 'The Title',
  review: '',
  recommend: false,
  nickname: '',
  location: '',
  email: '',
  buyForSelf: false,
  ageBracket: 1,
  gender: 1,
  graphics: 1,
  gameplay: 1,
  appeal: 1,
  ownershipBracket: 1,
  purchaseOnline: false,
  readReviews: false,
  recommendBGS: 1,
  meta: {
    helpful: 1,
    unhelpful: 1,
  },
},{
  _id: '3',
  gameId: 0,
  date: `${new Date()}`,
  overall: 1,
  title: 'The Title',
  review: '',
  recommend: false,
  nickname: '',
  location: '',
  email: '',
  buyForSelf: false,
  ageBracket: 1,
  gender: 1,
  graphics: 1,
  gameplay: 1,
  appeal: 1,
  ownershipBracket: 1,
  purchaseOnline: false,
  readReviews: false,
  recommendBGS: 1,
  meta: {
    helpful: 1,
    unhelpful: 1,
  },
}];

export default reviews;
